/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppWindowBar: typeof import('./src/components/AppWindowBar/index.vue')['default']
    HeadMenu: typeof import('./src/components/Layout/HeadMenu.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconPayFail: typeof import('./src/components/icons/IconPayFail.vue')['default']
    IconPaySuccess: typeof import('./src/components/icons/IconPaySuccess.vue')['default']
    IconSkin: typeof import('./src/components/icons/IconSkin.vue')['default']
    RadioGroup: typeof import('./src/components/Common/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenPannel: typeof import('./src/components/Layout/ScreenPannel.vue')['default']
    SidebarMenu: typeof import('./src/components/Layout/SidebarMenu.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VirtualList: typeof import('./src/components/Layout/VirtualList.vue')['default']
    VirtualPagination: typeof import('./src/components/Layout/VirtualPagination.vue')['default']
    VirtualSrollSameHeightVirtualList: typeof import('./src/components/virtualSrollSameHeightVirtualList.vue')['default']
  }
}
