/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./components/AppProvider/index.tsx')['default']
    AppWindowBar: typeof import('./components/AppWindowBar/index.vue')['default']
    HeadMenu: typeof import('./components/Layout/HeadMenu.vue')['default']
    IconDark: typeof import('./components/icons/IconDark.vue')['default']
    IconLight: typeof import('./components/icons/IconLight.vue')['default']
    IconPayFail: typeof import('./components/icons/IconPayFail.vue')['default']
    IconPaySuccess: typeof import('./components/icons/IconPaySuccess.vue')['default']
    IconSkin: typeof import('./components/icons/IconSkin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./components/Layout/SidebarMenu.vue')['default']
    VirtualPagination: typeof import('./components/Layout/VirtualPagination.vue')['default']
    VirtualSrollSameHeightVirtualList: typeof import('./components/virtualSrollSameHeightVirtualList.vue')['default']
  }
}
